version: 2

project_name: gitlab-tart-executor

before:
  hooks:
    - go mod download

builds:
  - main: cmd/gitlab-tart-executor/main.go
    ldflags: >
      -X github.com/cirruslabs/gitlab-tart-executor/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/gitlab-tart-executor/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: gitlab-tart-executor
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    dependencies:
      - "cirruslabs/cli/tart"
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/gitlab-tart-executor
    description: GitLab Runner Executor to run jobs inside isolated Tart VMs
    skip_upload: auto
